<?php

namespace Neoan3\Component\Song;

use Neoan3\Frame\Demo;

/**
 * Class SongController
 * @package Neoan3\Component\Song
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class SongController extends Demo{

    /**
    * GET: api.v1/song
    * GET: api.v1/song/{id}
    * GET: api.v1/song?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    function getSong(?string $id = null, array $params = []): array
    {
        // Restrict access to logged in users?
        // $this->Auth->restrict();
        // (or without dependency on Demo-Frame: $this->provider['auth']->restrict())
        if($id){
            // Retrieve a model?
            // return $this->loadModel(\Neoan3\Model\Song\SongModel::class)::get($id);
        }
        return $params;
    }

    /**
     * POST: api.v1/song
     * @param $body
     * @return array
     */
    function postSong(array $body): array
    {
        return $body;
    }
}
