<?php

namespace Neoan3\Component\Song;

use PHPUnit\Framework\TestCase;

/**
 * Class PostTest
 * Generated by neoan3-cli
 * @package Neoan3\Component\Song
 */
class SongTest extends TestCase
{
    private SongController $instance;
    function setUp(): void
    {
        $this->instance = new SongController();
    }
    
    function testGetSong()
    {
        $response = $this->instance->getSong('6a20', ['6b59'=>'8ab290']);
        $this->assertIsArray($response);
        $this->assertSame(['6b59'=>'8ab290'], $response);
    }

    function testPostSong()
    {
        $response = $this->instance->postSong(['a8de'=>'b696ff']);
        $this->assertIsArray($response);
        $this->assertSame(['a8de'=>'b696ff'], $response);
    }

}
