<?php

namespace Neoan3\Component\Artist;

use Neoan3\Frame\Demo;
use Neoan3\Model\Artist\ArtistModel;

/**
 * Class ArtistController
 * @package Neoan3\Component\Artist
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ArtistController extends Demo{

    /**
    * GET: api.v1/artist
    * GET: api.v1/artist/{id}
    * GET: api.v1/artist?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    function getArtist(?string $id = null, array $params = []): array
    {
        // Restrict access to logged in users?
        // $this->Auth->restrict();
        // (or without dependency on Demo-Frame: $this->provider['auth']->restrict())
        if($id){
            // Retrieve a model?
            return $this->loadModel(ArtistModel::class)::get($id);
        }
        return $params;
    }

    /**
     * POST: api.v1/artist
     * @param $body
     */
    function postArtist(array $body)
    {
        $this->loadModel(ArtistModel::class)::create($body);
    }
}
