<?php

namespace Neoan3\Component\Search;

use Neoan3\Frame\Demo;

/**
 * Class SearchController
 * @package Neoan3\Component\Search
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class SearchController extends Demo{

    /**
    * GET: api.v1/search
    * GET: api.v1/search/{id}
    * GET: api.v1/search?{query-string}
    * @param array $params
    * @return array
    */
    function getSearch(array $params = []): array
    {
        $results = [["artist"=> "Artist1", "album" => "album1", "art" => ""], ["artist"=> "Artist2", "album" => "album2"], ["artist"=> "Artist3", "album" => "album3"]];
        return $results;
    }

    /**
     * POST: api.v1/search
     * @param $body
     * @return array
     */
    function postSearch(array $body): array
    {
        return $body;
    }
}
