<?php

namespace Neoan3\Component\Album;
use Neoan3\Model\Album\AlbumModel;
use Neoan3\Frame\Demo;

/**
 * Class AlbumController
 * @package Neoan3\Component\Album
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class AlbumController extends Demo{

    /**
    * GET: api.v1/album
    * GET: api.v1/album/{id}
    * GET: api.v1/album?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    function getAlbum(?string $id = null, array $params = []): array
    {
        // Restrict access to logged in users?
        // $this->Auth->restrict();
        // (or without dependency on Demo-Frame: $this->provider['auth']->restrict())
        return $this->loadModel(\Neoan3\Model\Album\AlbumModel::class)::find([]);
        // if($id){
        //     // Retrieve a model?
        //     // return $this->loadModel(\Neoan3\Model\Album\AlbumModel::class)::get($id);
        // }
        // return $params;
    }

    /**
     * POST: api.v1/album
     * @param $body
     */
    function postAlbum(array $body)
    {
        $this->loadModel(AlbumModel::class)::create($body);
    }
}
