<?php

namespace Neoan3\Component\Review;

use Neoan3\Frame\Demo;

/**
 * Class ReviewController
 * @package Neoan3\Component\Review
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ReviewController extends Demo{

    /**
    * GET: api.v1/review
    * GET: api.v1/review/{id}
    * GET: api.v1/review?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    function getReview(?string $id = null, array $params = []): array
    {
        // Restrict access to logged in users?
        // $this->Auth->restrict();
        // (or without dependency on Demo-Frame: $this->provider['auth']->restrict())
        if($id){
            // Retrieve a model?
            // return $this->loadModel(\Neoan3\Model\Review\ReviewModel::class)::get($id);
        }
        return $params;
    }

    /**
     * POST: api.v1/review
     * @param $body
     * @return array
     */
    function postReview(array $body): array
    {
        return $body;
    }
}
