<?php

namespace Neoan3\Component\Review;

use PHPUnit\Framework\TestCase;

/**
 * Class PostTest
 * Generated by neoan3-cli
 * @package Neoan3\Component\Review
 */
class ReviewTest extends TestCase
{
    private ReviewController $instance;
    function setUp(): void
    {
        $this->instance = new ReviewController();
    }
    
    function testGetReview()
    {
        $response = $this->instance->getReview('7cca', ['f368'=>'4eb49f']);
        $this->assertIsArray($response);
        $this->assertSame(['f368'=>'4eb49f'], $response);
    }

    function testPostReview()
    {
        $response = $this->instance->postReview(['e5a7'=>'8d0e86']);
        $this->assertIsArray($response);
        $this->assertSame(['e5a7'=>'8d0e86'], $response);
    }

}
