<?php

namespace Neoan3\Component\Queue;
use Neoan3\Model\Queue\QueueModel;
use Neoan3\Frame\Demo;

/**
 * Class QueueController
 * @package Neoan3\Component\Queue
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class QueueController extends Demo{

    /**
    * GET: api.v1/queue
    * GET: api.v1/queue/{id}
    * GET: api.v1/queue?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    function getQueue(?string $id = null, array $params = [])//: array
    {
        // Restrict access to logged in users?
        // $this->Auth->restrict();
        // (or without dependency on Demo-Frame: $this->provider['auth']->restrict())
        if($id){
            // Retrieve a model?
            return $this->loadModel(\Neoan3\Model\Queue\QueueModel::class)::complete($id);
        }
        //return $this->loadModel(\Neoan3\Model\Queue\QueueModel::class)::complete();
    }

    /**
     * POST: api.v1/queue
     * @param $body
     */
    function postQueue(array $body)
    {
        return $this->loadModel(QueueModel::class)::create($body);
    }

    function putQueue(array $params)
    {
        return $this->loadModel(QueueModel::class)::position($params);
    }

}
